# -*- coding: utf-8 -*-
"""YWKit.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/YanwenLai/forTAClass/blob/main/YWKit.ipynb

這是12/22教學用示範
"""

def mySum():
    x, y = int(input('請輸入第1個數字: ')), int(input('請輸入第2個數字: '))
    print(f'你輸了入{x}與{y}，他們的和是 {x + y}')

def mySub():
    x, y = int(input('請輸入第1個數字: ')), int(input('請輸入第2個數字: '))
    print(f'{x} - {y} = {x - y}')

